### ISSUE TITLE
Configure Account freeze on different confirmation password

### ISSUE THREAD

**Issue by vianneynara** [vianneynara/Konsmail#13]
![image](https://github.com/vianneynara/Konsmail/assets/98963440/7dea24bf-ef76-4147-9af6-848ba53467ba)

(please ignore the double new password, it's fixed already in the latest commits).
This can be reproduced by:
1. Opening configuring your account window
2. trying to change password
3. filling the new password and **confirm new password** field with different values.
4. clicking "Save" button

PS: Might also happen when changing First name or last name?
tag: @Trustacean

**Comment by Trustacean** [comment]
fixed

**Comment by vianneynara** [comment]
Resolved in PR #14
